apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment
  labels:
    app: go-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: go-webapp-container
          image: quay.io/jpolonip/go-argocd-workshop:dev-7b481465baef87837e4c1e9e12af23191f18c079
